# Generated by Django 4.2 on 2024-11-17 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanRehabilitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesiones_totales', models.IntegerField()),
                ('sesiones_completadas', models.IntegerField(default=0)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_rehabilitacion', to='pacientes.paciente')),
            ],
        ),
    ]
